Future/header
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #1
Opened 2023-01-10 13:45 UTC by DimaTeniuta

1. Add header
2. Add General routing
3. Add a general page structure

2023-01-10 16:48 UTC, darnnng approved these changes

2023-01-10 19:47 UTC, tatsmaki requested changes

2023-01-10 19:47 UTC, tatsmaki commented on src/App.tsx
> +    <BrowserRouter>
BrowserRouter перенес бы внутрь AppRouter

2023-01-10 19:47 UTC, tatsmaki commented on src/utils/variables.ts
> +export enum Languages {
возможные языки нужно будет брать с бека

2023-01-10 19:47 UTC, tatsmaki commented on src/route/PublicRoute.tsx
> +  return <Suspense fallback={<Spinner />}>{children}</Suspense>;
используй Suspense один раз в роутере над всеми ленивыми страницами

2023-01-10 19:47 UTC, tatsmaki commented on src/route/PrivateRoute.tsx
> +  return <Suspense fallback={<Spinner />}>{children}</Suspense>;
используй Suspense один раз в роутере над всеми ленивыми страницами

2023-01-10 19:47 UTC, tatsmaki commented on src/route/AppRouter.tsx
> +            <Suspense fallback={<Spinner />}>
не могу понять для чего здесь саспенс?

2023-01-10 19:47 UTC, tatsmaki commented on src/utils/routeVariables.ts
> +  HOME = '/',
думаю RoutePath и Languages это константы, constants, а не utils

2023-01-10 19:47 UTC, tatsmaki commented on src/index.scss
> +    padding-top: 65px;
https://mui.com/material-ui/react-css-baseline/

надо убрать index.scss

2023-01-10 19:47 UTC, tatsmaki commented on src/components/UI/AuthButtons/AuthButtons.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
так а что будет если локация изменится? текст кнопки не поменяется? что тут вообще происходит, что такое индекс кнопки?

2023-01-11 06:27 UTC, DimaTeniuta commented on src/App.tsx
> +    <BrowserRouter>
Сделал

2023-01-11 06:28 UTC, DimaTeniuta commented on src/route/AppRouter.tsx
> +            <Suspense fallback={<Spinner />}>
Удалил

2023-01-11 07:19 UTC, DimaTeniuta commented on src/utils/routeVariables.ts
> +  HOME = '/',
Перенес

2023-01-11 07:29 UTC, DimaTeniuta commented on src/route/PublicRoute.tsx
> +  return <Suspense fallback={<Spinner />}>{children}</Suspense>;
Я хочу чтобы Spinner был показан вместо страницы, но при этом хедер и футер были на месте (Вариант с обернуть все не подходит). А внутри Routes должны быть только Route компоненты.

2023-01-11 11:06 UTC, DimaTeniuta commented on src/index.scss
> +    padding-top: 65px;
Убрал

2023-01-11 11:30 UTC, DimaTeniuta commented on src/components/UI/AuthButtons/AuthButtons.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Tabs из MUI принимает индекс кнопок для подсветки активной. Для этого и создал константы, чтобы не было magic number.
Локализация еще не сделана, названия кнопок будут заменены.

2023-01-13 09:42 UTC, tatsmaki approved these changes

2023-01-13 09:42 UTC, merged