Future/empoyees private
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #10
Opened 2023-01-18 08:32 UTC by DimaTeniuta

1. Добавил роуты для переходов со страницы Empoyees на дочерние роуты
2. Добавил отображение имени пользователя или его email в breadcrumbs

2023-01-18 11:30 UTC, darnnng commented on src/graphql/query/user.ts
> +`;
может запрос поместить в папку src/graphql/users/query чтоб структура была более менее похожа?  или папку назвать queries вместо query и туда запросы все

2023-01-18 13:42 UTC, DimaTeniuta commented on src/graphql/query/user.ts
> +`;
Переименовал папку и переместил файлы

2023-01-18 13:51 UTC, darnnng approved these changes

2023-01-19 11:46 UTC, tatsmaki requested changes

2023-01-19 11:46 UTC, tatsmaki commented on src/components/UI/EmployeesNavButtons/EmployeesNavButtons.tsx
> +        <Styled.TabNav
можно попробовать вынести данные в массив и отображать табы итерацией

2023-01-19 11:50 UTC, tatsmaki requested changes

2023-01-19 11:50 UTC, tatsmaki commented on src/route/AppRouter.tsx
> +                element={<PrivateRoute>{<EmployeesProfilePage />}</PrivateRoute>}
повторяющийся вложенный PrivateRoute

2023-01-19 12:00 UTC, tatsmaki approved these changes

2023-01-19 12:03 UTC, DimaTeniuta commented on src/route/AppRouter.tsx
> +                element={<PrivateRoute>{<EmployeesProfilePage />}</PrivateRoute>}
Исправил

2023-01-19 12:23 UTC, DimaTeniuta commented on src/components/UI/EmployeesNavButtons/EmployeesNavButtons.tsx
> +        <Styled.TabNav
Вынес в массив

2023-01-19 12:23 UTC, merged