Future/table
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #12
Opened 2023-01-18 16:07 UTC by darnnng

1. Search box and Add button;
2. Began doing  table template and reusable table parts;
3. Table header for users

2023-01-18 21:01 UTC, DimaTeniuta requested changes

2023-01-18 21:01 UTC, DimaTeniuta commented on src/components/Table/helpers/AddEmployeeBtn/AddEmployeeBtn.tsx
> +      <ButtonAddEmployee disabled={user?.role == UserRoles.Employee}>
https://eslint.org/docs/latest/rules/eqeqeq На счет oператора "двойное равно"
Думаю, что пользователю не стоит вообще показывать кнопку, которая ему не доступна.
Fragment нужен для возврата нескольких элементов без дополнительной обертки.

2023-01-18 21:01 UTC, DimaTeniuta commented on src/components/Table/TableHeader/TableHeaderCell/TableHeaderCell.tsx
> +    </>
Fragment нужен для возврата нескольких элементов без дополнительной обертки

2023-01-18 21:01 UTC, DimaTeniuta commented on src/components/Table/helpers/AddEmployeeBtn/AddEmployeeBtn.styles.ts
> +  marginTop: '5px',
Думаю, что не очень хорошая идея центрировать элементы таким образом. (Вдруг завтра нужно будет добавить еще одну кнопку с другим размером высоты.) Лучше родителю добавить `alignItems: 'center'` и убрать у TextField жестко заданную высоту.

2023-01-18 21:01 UTC, DimaTeniuta commented on src/components/Table/helpers/Search/SearchInput.tsx
> +      sx={{ p: '5px', height: '30px' }}
Писал про центрирование.

2023-01-18 21:01 UTC, DimaTeniuta commented on src/components/Table/template/templateTable.tsx
> +export const createTable = (): FC<TableProps> => TableComponent;
Нужна ли дополнительная функция? Может можно сразу экспортировать ` export const TableComponent = memo(Table);`

2023-01-18 21:01 UTC, DimaTeniuta commented on src/pages/EmployeesPage/EmployeesPage.styles.ts
> +  margin: 'auto',
Обернув в  Container из MUI и задав maxWidth не придется руками прописывать стили в двух компонентах. 
![image](https://user-images.githubusercontent.com/93836691/213292474-ddaf25a0-9e3f-4afa-9a9b-4a558dcc1186.png)

2023-01-18 21:01 UTC, DimaTeniuta commented on src/components/Table/TableHeader/TableHeaderComponent.tsx
> +        const { columnName } = col;
`{columns.map(({ columnName }) => {`

2023-01-19 09:44 UTC, darnnng commented on src/components/Table/TableHeader/TableHeaderComponent.tsx
> +        const { columnName } = col;
исправила

2023-01-19 09:45 UTC, darnnng commented on src/components/Table/helpers/Search/SearchInput.tsx
> +      sx={{ p: '5px', height: '30px' }}
стили подправила

2023-01-19 09:46 UTC, darnnng commented on src/components/Table/helpers/AddEmployeeBtn/AddEmployeeBtn.tsx
> +      <ButtonAddEmployee disabled={user?.role == UserRoles.Employee}>
кнопка тогда только для админа теперь видна, фрагмент оставила потому что там выражение теперь внутри

2023-01-19 13:32 UTC, DimaTeniuta approved these changes

2023-01-20 08:45 UTC, tatsmaki requested changes

2023-01-20 08:45 UTC, tatsmaki commented on src/components/Table/TableHeader/TableHeaderCell/TableHeaderCell.tsx
> +const TableHeaderCell = ({ name }: TableHeaderCellProps) => {
выглядит будто это нужно застилизовать в глобальной теме

2023-01-20 08:46 UTC, tatsmaki approved these changes

2023-01-20 11:05 UTC, merged