Future/table rows
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #15
Opened 2023-01-20 09:54 UTC by darnnng

1. Получение данных о всех users;
2. Отображение этих данных в таблице;

2023-01-20 11:02 UTC, DimaTeniuta requested changes

2023-01-20 11:02 UTC, DimaTeniuta commented on src/components/Table/template/templateTable.types.ts
> +};
`export type Item = Record<string, string>;`

2023-01-20 11:25 UTC, darnnng commented on src/components/Table/template/templateTable.types.ts
> +};
исправила

2023-01-20 11:56 UTC, DimaTeniuta approved these changes

2023-01-23 09:19 UTC, tatsmaki commented on src/components/Table/template/templateTable.tsx
> +              {item.email ? (
предлагаю добавить возможность указывать вложенные поля
например
header = ['profile.avatar', 'email', 'first_name', ...]

2023-01-24 13:43 UTC, DimaTeniuta approved these changes

2023-01-25 00:31 UTC, tatsmaki commented on src/components/Table/helpers/Avatar/Avatar.tsx
> +      <Avatar src={item?.avatar}>{item?.email[0].toUpperCase()}</Avatar>
инициалы или первая буква почты

2023-01-25 00:32 UTC, tatsmaki commented on src/components/Table/template/templateTable.tsx
> +                <ColumnCellComponent key={columnKey} item={item} columnKey={columnKey} />
хорош, можно было бы только добавить компонент по умолчанию, а то указывать каждый раз TableRowCell надоест

2023-01-25 00:34 UTC, tatsmaki commented on src/pages/EmployeesPage/TableData/UsersTableRows.ts
> +    id: user?.id,
не совсем понимаю зачем менять интерфейсы, но пожалуйста, главное не забудьте потом с чем работаете

2023-01-25 08:38 UTC, tatsmaki approved these changes

2023-01-25 08:50 UTC, merged