Future/admin buttons
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #29
Opened 2023-01-26 16:45 UTC by darnnng

1. Меню выпадающее
![image](https://user-images.githubusercontent.com/87519112/214895717-1e9bcce6-b7af-4a77-a61c-8166118a229a.png)
2. Админ может удалять usera
3. По нажатию update/ аватарки админ может обновлять информацию/аватар usera и сам user может обновлять свою информацию/ аватар

2023-01-26 19:51 UTC, DimaTeniuta requested changes

2023-01-26 19:51 UTC, DimaTeniuta commented on src/components/Table/TableRows/TableRowComponent.tsx
> +  };
Думаю достаточно будет навигации на `employees/:id/profile`
А там уже вся логика для обновления юзера есть

2023-01-26 19:51 UTC, DimaTeniuta commented on src/components/Table/TableRows/TableRowComponent.tsx
> +          disabled={user?.id !== id && user?.role !== UserRoles.Admin}
`disabled={user?.id !== id && !isAdmin}`

2023-01-26 19:51 UTC, DimaTeniuta commented on src/components/Table/helpers/Avatar/Avatar.tsx
> +  const user = useUser();
Тоже думаю этот функционал должен быть на вложенных страницах. Иначе вложенные страницы станут бесполезны для роли admin, так как нет другого роута

2023-01-27 10:27 UTC, DimaTeniuta approved these changes

2023-01-28 20:49 UTC, DimaTeniuta approved these changes

2023-01-30 13:21 UTC, tatsmaki requested changes

2023-01-30 13:21 UTC, tatsmaki commented on src/components/Table/TableRows/TableRowComponent.tsx
> +      <Menu
вынеси меню в отдельный компонент, раздели логику

2023-01-30 13:29 UTC, tatsmaki approved these changes

2023-01-30 13:49 UTC, merged