Future/auth
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #3
Opened 2023-01-13 12:12 UTC by darnnng

1. Login and signup queries;
2. Login page;
3. SignUp page;
4. Small changes in routes and profile with the usage of reactive vars

2023-01-13 13:42 UTC, DimaTeniuta requested changes

2023-01-13 13:42 UTC, DimaTeniuta commented on src/interfaces/results/IAuthResult.ts
> +}
Думаю нужно или везде использовать префикс I для интерфейсов или не использовать

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/LogInPage/LogInPage.tsx
> +  const [login] = useLazyQuery(LOGIN);
Хук возвращает во втором параметре объект с полем loading, возможно можно было бы показать какой-нибудь лоадер пользователю во время загрузки или же использовать loading button из Material UI

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/LogInPage/LogInPage.tsx
> +    setHiddenPassword((visability) => !visability);
visibility

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/LogInPage/LogInPage.tsx
> +                  }}
этот код повторяется в компоненте SignUpPage возможно лучше его вынести в styled компонент

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/SignUpPage/SignUp.styles.ts
> +  position: 'fixed',
Из-за позиционирования на мобильных разрешениях отсутствует скролл

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/SignUpPage/SignUpPage.tsx
> +  const [signUp] = useMutation(SIGNUP);
Здесь тоже есть поле loading, чтобы показать лоадер

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/SignUpPage/SignUpPage.tsx
> +    setHiddenPassword((visability) => !visability);
visibility

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/LogInPage/LogInPage.tsx
> +                <ValidationError>{errors.password?.message}</ValidationError>
у TextField есть поле helperText в которое передается текст ошибки, а в поле error логическое значение (к примеру тот же текст приведенный к логическому типу)

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/LogInPage/LogInPage.tsx
> +                <ValidationError>{errors.email?.message}</ValidationError>
ниже написал

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/SignUpPage/SignUpPage.tsx
> +                <ValidationError>{errors.email?.message}</ValidationError>
Выше писал про это

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/SignUpPage/SignUpPage.tsx
> +                <ValidationError>{errors.password?.message}</ValidationError>
Выше писал про это

2023-01-13 13:42 UTC, DimaTeniuta commented on src/pages/SignUpPage/SignUpPage.tsx
> +                  }}
Выше писал про повторение кода

2023-01-13 13:57 UTC, tatsmaki commented on src/interfaces/results/IAuthResult.ts
> +}
да, для интерфейсов I префикс, либо через type описывай.
и еще типизацию запросов удобно хранить вместе с самими запросами (в одной папке).
так же как и типизацию формы (IFormInput) вместе с компонентом формы

2023-01-13 14:02 UTC, tatsmaki commented on src/utils/validationSchema.ts
> +import * as yup from 'yup';
более аккуратный импорт

2023-01-13 20:16 UTC, darnnng commented on src/interfaces/results/IAuthResult.ts
> +}
исправила

2023-01-13 20:20 UTC, darnnng commented on src/pages/LogInPage/LogInPage.tsx
> +                  }}
оставила стили в sx потому что в styled component не могу передать component={NavLink}

2023-01-13 20:55 UTC, darnnng commented on src/pages/LogInPage/LogInPage.tsx
> +                  }}
все, исправила)

2023-01-13 20:55 UTC, darnnng commented on src/pages/LogInPage/LogInPage.tsx
> +    setHiddenPassword((visability) => !visability);
исправила

2023-01-13 20:56 UTC, darnnng commented on src/utils/validationSchema.ts
> +import * as yup from 'yup';
исправила

2023-01-13 21:18 UTC, darnnng commented on src/pages/LogInPage/LogInPage.tsx
> +  const [login] = useLazyQuery(LOGIN);
добавила loading button

2023-01-13 21:26 UTC, darnnng commented on src/pages/LogInPage/LogInPage.tsx
> +                <ValidationError>{errors.password?.message}</ValidationError>
исправила)

2023-01-13 21:34 UTC, darnnng commented on src/pages/SignUpPage/SignUp.styles.ts
> +  position: 'fixed',
исправила

2023-01-14 13:43 UTC, DimaTeniuta approved these changes

2023-01-17 16:32 UTC, merged