Future/create user button
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #35
Opened 2023-01-29 13:06 UTC by darnnng

Создание админом нового пользователя, модальное окно для создания пользователя
![image](https://user-images.githubusercontent.com/87519112/215327908-fe5c856c-c2dc-446a-ae2c-4c3222606e37.png)

2023-01-29 15:22 UTC, DimaTeniuta requested changes

2023-01-29 15:22 UTC, DimaTeniuta commented on src/pages/EmployeesPage/EmployeesModal/EmployeesModal.tsx
> +          />
Нужна валидация. Поле является обязательным

2023-01-30 13:32 UTC, tatsmaki approved these changes, later dismissed

2023-01-30 13:49 UTC, DimaTeniuta approved these changes, later dismissed

2023-01-30 14:00 UTC, merged