Future/notifire
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #4
Opened 2023-01-13 12:43 UTC by DimaTeniuta

1. Добавил компонент Notifire.
2. Добавил класс для управлением Notifire.

2023-01-13 14:07 UTC, tatsmaki requested changes

2023-01-13 14:07 UTC, tatsmaki commented on src/components/UI/Notifier/Notifier.tsx
> +  const open = useReactiveVar(notificationService.isOpen$);
го контейнер для массива уведомлений (на картинке пример того что может быть несколько ошибок, разных, одинаковых подряд)
![image](https://user-images.githubusercontent.com/61022192/212338595-62af0188-7204-4dc9-b6ec-14c57acc5320.png)

2023-01-13 20:23 UTC, DimaTeniuta commented on src/components/UI/Notifier/Notifier.tsx
> +  const open = useReactiveVar(notificationService.isOpen$);
Изменил

2023-01-14 20:02 UTC, darnnng commented on src/utils/convertApolloError.ts
> +    return 'Email has already exists';
Email already exists

2023-01-14 20:06 UTC, darnnng commented on src/utils/convertApolloError.ts
> +    return 'Email has already exists';
Email already exists

2023-01-14 20:21 UTC, DimaTeniuta commented on src/utils/convertApolloError.ts
> +    return 'Email has already exists';
Исправил

2023-01-14 20:23 UTC, darnnng approved these changes

2023-01-17 16:34 UTC, merged