Future/projects page
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #50
Opened 2023-02-01 09:34 UTC by darnnng

1. Projects table
![image](https://user-images.githubusercontent.com/87519112/216005318-895ec73a-10bc-4baa-81ae-32d09df612e2.png)
2. Deletion of projects
3. Modal window for creating project
![image](https://user-images.githubusercontent.com/87519112/216005067-a2717d56-5e65-418d-9392-f81df63490bd.png)

2023-02-01 11:47 UTC, DimaTeniuta requested changes

2023-02-01 11:47 UTC, DimaTeniuta commented on src/components/UI/DatePicker/DatePicker.tsx
> +              />
1. Нет сообщений валидации.
2. Кнопка сабмита становится активной только если явно выбрать 2 даты.
3. Нужна валидация для того, чтобы дата окончания не была меньше даты начала.

2023-02-01 11:47 UTC, DimaTeniuta commented on src/graphql/cache/createProject.ts
> +  };
Не нужная переменная. Можно сразу передавать `projects: [data?.createProject, ...allProjects.projects],`

2023-02-02 16:56 UTC, DimaTeniuta requested changes

2023-02-02 16:56 UTC, DimaTeniuta commented on src/components/UI/DatePicker/DatePicker.tsx
> +                helperText={fieldState.error?.message || ' '}
Чтобы форма выглядела одинаково `helperText={fieldState.error?.message}`

2023-02-02 16:56 UTC, DimaTeniuta commented on src/components/UI/DatePicker/DatePicker.tsx
> +              trigger!('endDate');
Все же лучше добавить условие, так как пропс опциональный `trigger && trigger('endDate');`

2023-02-02 16:56 UTC, DimaTeniuta commented on src/utils/validationSchema.ts
> +  endDate: date().when('startDate', (startDate, schema) => startDate && schema.min(startDate)),
Дефолтное сообщение лучше заменить на что-нибудь типа `startDate && schema.min(startDate, 'endDate must be bigger than startDate'))`

2023-02-02 19:23 UTC, DimaTeniuta approved these changes

2023-02-06 19:18 UTC, tatsmaki requested changes

2023-02-06 19:18 UTC, tatsmaki commented on package.json
> +    "date-fns": "^2.29.3",
мне кажется тут 2 либы для форматирования
оставь только одну

2023-02-06 19:18 UTC, tatsmaki commented on src/components/pages/ProjectsPage/ProjectsCreateModal/ProjectsCreateModal.tsx
> +        <form onSubmit={handleSubmit(onSubmit as TFormSubmit)} autoComplete="off">
для чего тут as?

2023-02-06 19:18 UTC, tatsmaki commented on src/components/pages/ProjectsPage/ProjectsCreateModal/ProjectsCreateModal.tsx
> +            helperText={errors.description?.message as string}
message это string
as не избавит тебя от проблемы, что в рантайме сюда попадает undefined
errors.description?.message || ""

2023-02-09 07:49 UTC, tatsmaki approved these changes

2023-02-09 07:52 UTC, merged