Future/project details
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #55
Opened 2023-02-03 14:36 UTC by darnnng

1. Project details page
![image](https://user-images.githubusercontent.com/87519112/216622046-54cc5e58-11a6-459b-89b0-944c978a2899.png)
2. Update project modal
![image](https://user-images.githubusercontent.com/87519112/216622250-a329fa68-4c2a-461a-aa75-136ee86e515c.png)

2023-02-03 19:24 UTC, DimaTeniuta requested changes

2023-02-03 19:24 UTC, DimaTeniuta commented on src/components/pages/ProjectsDetailsPage/ProjectDetailsPage.tsx
> +            </PrivateButton>
![image](https://user-images.githubusercontent.com/93836691/216675269-86dffb41-022b-421a-8dd4-bb2feebbd134.png)
Верстка ломается

2023-02-03 19:24 UTC, DimaTeniuta commented on src/components/pages/ProjectsDetailsPage/ProjectDetailsPage.tsx
> +              <Styled.InfoWrapper>
![image](https://user-images.githubusercontent.com/93836691/216677747-c8652917-ad3f-4637-83a9-fc69771f7c28.png)
Как вариант для InfoWrapper ` whiteSpace: 'pre-wrap',
  wordWrap: 'break-word',
  wordBreak: 'break-word',`

2023-02-03 19:24 UTC, DimaTeniuta commented on src/components/pages/ProjectsDetailsPage/ProjectDetailsPage.tsx
> +                    : data?.project?.description || '-'}
Если это ограничение из-за того, что ломается верстка, то комментарий выше + `whiteSpace: 'nowrap'` для RowTitleTypography поможет

2023-02-03 19:24 UTC, DimaTeniuta commented on src/components/pages/ProjectsDetailsPage/Row/Row.tsx
> +import * as Styled from '../../EmployeesProfilePage/EmployeesProfilePage.styles';
эти же стили описаны и в `ProjectsDetailsPage.styles.ts`.  
Эти стили используются на нескольких страницах. В ветке `future/cv-details`  компонент `Row` уже вынесен на верхний уровень в папке `components`

2023-02-03 20:58 UTC, darnnng commented on src/components/pages/ProjectsDetailsPage/ProjectDetailsPage.tsx
> +                    : data?.project?.description || '-'}
исправила верстку

2023-02-04 06:29 UTC, DimaTeniuta approved these changes

2023-02-06 19:20 UTC, tatsmaki requested changes

2023-02-06 19:20 UTC, tatsmaki commented on src/components/pages/ProjectsDetailsPage/ProjectUpdateModal/ProjectUpdateModal.tsx
> +            helperText={errors.name?.message as string}
as

2023-02-06 19:20 UTC, tatsmaki commented on src/components/pages/ProjectsDetailsPage/ProjectUpdateModal/ProjectUpdateModal.tsx
> +        <form onSubmit={handleSubmit(onSubmit as TFormSubmit)} autoComplete="off">
as

2023-02-06 19:20 UTC, tatsmaki commented on src/components/pages/ProjectsPage/ProjectsCreateModal/ProjectsCreateModal.tsx
> +            helperText={errors.internalName?.message as string}
as

2023-02-07 15:17 UTC, tatsmaki approved these changes

2023-02-07 15:22 UTC, merged