Future/cvs projects
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #57
Opened 2023-02-04 16:25 UTC by DimaTeniuta

1. Добавил страницу на роуте `cvs/:id/projects`
2. На странице отображена таблица с проектами
![image](https://user-images.githubusercontent.com/93836691/216778233-46bbf678-ca2b-43ce-a917-6feb53b16b82.png)
3. Есть кнопка для открытия модального окна
4. В модальном окне можно изменить проекты
![image](https://user-images.githubusercontent.com/93836691/216778287-a8a12630-b282-4838-a23e-bbb4d8249f38.png)
![image](https://user-images.githubusercontent.com/93836691/216778301-865de389-a20f-440a-94dd-24d213b38492.png)
close #54

2023-02-05 18:10 UTC, darnnng approved these changes

2023-02-06 19:22 UTC, tatsmaki requested changes

2023-02-06 19:22 UTC, tatsmaki commented on package.json
> +    "date-fns": "^2.29.3",
2 либы для формата

2023-02-06 19:22 UTC, tatsmaki commented on src/components/pages/ProjectsPage/ProjectsCreateModal/ProjectsCreateModal.tsx
> +            helperText={errors.name?.message as string}
errors.name?.message || ""
без as, поменьше as, молю

2023-02-07 10:11 UTC, DimaTeniuta commented on src/components/pages/ProjectsPage/ProjectsCreateModal/ProjectsCreateModal.tsx
> +            helperText={errors.name?.message as string}
Исправил

2023-02-07 11:15 UTC, DimaTeniuta commented on package.json
> +    "date-fns": "^2.29.3",
Удалил ненужные либы, метод `format` заменил на функцию `formatDate`

2023-02-07 15:16 UTC, tatsmaki approved these changes

2023-02-07 15:47 UTC, merged