Future/departments
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #64
Opened 2023-02-06 13:39 UTC by darnnng

1. Departments page;
2. Ability for admin to delete department
3. Modal windows for creating/updating department

2023-02-06 15:15 UTC, DimaTeniuta requested changes

2023-02-06 15:15 UTC, DimaTeniuta commented on src/components/pages/DepartmentsPage/DepartmentsPage.tsx
> +            titleCreateBtn="Add department"
Возможно нужна более короткая надпись, что-то вроде "Create" или "Add" и также gap между инпутом и кнопкой на мобильном разрешении
![image](https://user-images.githubusercontent.com/93836691/216990441-d782792c-b7f2-4dd7-b31c-40efb16e3e85.png)

2023-02-06 15:15 UTC, DimaTeniuta commented on src/components/pages/DepartmentsPage/DepartmentCreate/DepartmentCreateModal.tsx
> +    <ModalWindow title={'Create new department'} onClose={onClose} open={open}>
Возможно нужен более короткий заголовок, так как кнопка наезжает на текст на мобильном разрешении.
![image](https://user-images.githubusercontent.com/93836691/216991197-b89a5427-f0a1-4a37-a48a-c133cca6015f.png)

2023-02-06 15:15 UTC, DimaTeniuta commented on src/components/Table/template/templateTable.tsx
> +                  setItem={setItem}
пропс handleUpdate может ведь и отсутствовать?

2023-02-06 15:15 UTC, DimaTeniuta commented on src/components/pages/DepartmentsPage/DepartmentsAdditionalBtns/DepartmentsAdditionalBtns.tsx
> +    })!;
Думаю это утверждение излишне

2023-02-06 15:15 UTC, DimaTeniuta commented on src/components/pages/DepartmentsPage/DepartmentsPage.tsx
> +            setItem={setDepartment}
Создам issue для замены этого на глобальное состояние

2023-02-06 19:24 UTC, tatsmaki requested changes

2023-02-06 19:24 UTC, tatsmaki commented on src/components/pages/DepartmentsPage/DepartmentCreate/DepartmentCreateModal.tsx
> +  if (error) {
никогда не вызывай функции, меняющие какое-либо состояние внутри рендера

2023-02-06 19:24 UTC, tatsmaki commented on src/components/pages/DepartmentsPage/DepartmentUpdate/DepartmentUpdate.tsx
> +    onClose();
same

2023-02-06 19:24 UTC, tatsmaki commented on src/components/pages/DepartmentsPage/DepartmentsPage.tsx
> +    navigate(`/${RoutePath.LOGIN}`, { replace: true });
same

2023-02-07 15:17 UTC, tatsmaki approved these changes

2023-02-07 18:12 UTC, DimaTeniuta approved these changes

2023-02-07 18:18 UTC, merged