Refactor/fix error loading
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #72
Opened 2023-02-08 14:02 UTC by darnnng

1. добавила недостающие зависимости к useeffect
2. переместила loading внутрь return

2023-02-08 19:47 UTC, tatsmaki requested changes

2023-02-08 19:47 UTC, tatsmaki commented on src/components/pages/CvsProjectsPage/UpdateModal/UpdateModal.tsx
> +    if (error) {
лучше разделить на 2 эффекта
а вообще почему не onError?
![image](https://user-images.githubusercontent.com/61022192/217635588-4e1e5cb5-6b23-49a2-af8e-7fa60b08e306.png)

2023-02-08 19:55 UTC, DimaTeniuta requested changes

2023-02-08 19:55 UTC, DimaTeniuta commented on src/components/pages/CvsProjectsPage/UpdateModal/UpdateModal.tsx
> +    }
думаю нужно добавить обработку ошибки из `useQuery<ICvQueryResult>(CV, { variables: { id },});`

2023-02-09 09:54 UTC, darnnng commented on src/components/pages/CvsProjectsPage/UpdateModal/UpdateModal.tsx
> +    if (error) {
исправила

2023-02-09 09:55 UTC, darnnng commented on src/components/pages/CvsProjectsPage/UpdateModal/UpdateModal.tsx
> +    }
исправила

2023-02-09 20:06 UTC, DimaTeniuta approved these changes

2023-02-13 10:02 UTC, merged