Future/skills
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #73
Opened 2023-02-09 07:40 UTC by darnnng

Skills page table, ability for admin to delete, update and create skill

2023-02-09 19:56 UTC, DimaTeniuta requested changes

2023-02-09 19:56 UTC, DimaTeniuta commented on src/components/pages/SkillsPage/SkillCreate/SkillCreateModal.tsx
> +      })
`.catch((err: TError) => console.error(err.message))`

2023-02-09 19:56 UTC, DimaTeniuta commented on src/components/pages/SkillsPage/SkillCreate/SkillCreateModal.tsx
> +
Думаю пустая строка не нужна

2023-02-09 19:56 UTC, DimaTeniuta commented on src/components/pages/SkillsPage/SkillUpdate/SkillUpdateModal.tsx
> +  const skill: Pick<Partial<ISkill>, keyof ISkill> = useReactiveVar(modalService.modalData$);
Ты отправляешь в modalService `{ id: string, name: string }` а здесь еще и тип create_at устанавливаешь. Нужен отдельный интерфейс

2023-02-09 19:56 UTC, DimaTeniuta commented on src/components/pages/SkillsPage/SkillsAdditionalBtns/SkillsAdditionalBtns.tsx
> +    });
Думаю типизация явная не нужна. 
Можно использовать как ` modalService.setModalData('Update skill', SkillsUpdateModal, { name, id });`

2023-02-09 19:56 UTC, DimaTeniuta commented on src/components/pages/SkillsPage/SkillsPage.tsx
> +  }, [error, navigate]);
Давай приведем к общему виду 
![image](https://user-images.githubusercontent.com/93836691/217922552-b923d4b2-ffc0-440b-84f3-a9e10c663846.png)

2023-02-10 07:14 UTC, darnnng commented on src/components/pages/SkillsPage/SkillsPage.tsx
> +  }, [error, navigate]);
исправила все)

2023-02-10 10:28 UTC, DimaTeniuta approved these changes

2023-02-10 16:30 UTC, tatsmaki approved these changes

2023-02-10 16:33 UTC, merged