feat:add error boundary
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #8
Opened 2023-01-17 17:13 UTC by darnnng

1.Error Boundary;
2.Error page

2023-01-17 18:23 UTC, DimaTeniuta requested changes

2023-01-17 18:23 UTC, DimaTeniuta commented on src/pages/ErrorPage/ErrorPage.tsx
> +            fontWeight: 'bold',
лучше вынести в styled

2023-01-17 18:23 UTC, DimaTeniuta commented on src/pages/ErrorPage/ErrorPage.tsx
> +            />
Инлайн стили. Лучше вынести в styled
Также добавить адаптивность. К примеру 
![image](https://user-images.githubusercontent.com/93836691/212979278-a613553c-74b8-4fe2-a802-af8615cb5010.png)

2023-01-17 18:23 UTC, DimaTeniuta commented on src/pages/ErrorPage/ErrorPage.tsx
> +              >
Нужен также роут для авторизованного пользователя, так как публичные роуты ему не доступны

2023-01-17 18:23 UTC, DimaTeniuta commented on src/pages/ErrorPage/ErrorPage.tsx
> +              }}
Лучше вынести в функцию, ивент она получит по дефолту. В других случаях поможет замыкание, чтобы не использовать инлайн функции

2023-01-17 18:23 UTC, DimaTeniuta commented on src/pages/ErrorPage/ErrorPage.tsx
> +        <Grid container justifyContent="center" columnGap={2} mt="40px">
на 320px нет gap, так как кнопки перестраиваются. Можно заменить columnGap на gap

2023-01-17 19:14 UTC, darnnng commented on src/pages/ErrorPage/ErrorPage.tsx
> +        <Grid container justifyContent="center" columnGap={2} mt="40px">
исправила

2023-01-17 19:14 UTC, darnnng commented on src/pages/ErrorPage/ErrorPage.tsx
> +              }}
исправила

2023-01-17 19:14 UTC, darnnng commented on src/pages/ErrorPage/ErrorPage.tsx
> +              >
исправила

2023-01-17 19:15 UTC, darnnng commented on src/pages/ErrorPage/ErrorPage.tsx
> +            />
стили исправила

2023-01-17 19:51 UTC, DimaTeniuta requested changes

2023-01-17 19:51 UTC, DimaTeniuta commented on src/pages/ErrorPage/ErrorPage.tsx
> +            )}{' '}
{' '} это наверно не нужно

2023-01-17 19:51 UTC, DimaTeniuta commented on src/pages/ErrorPage/ErrorPage.tsx
> +            <Grid item>
pageNotFound && <Grid item>

2023-01-18 05:42 UTC, DimaTeniuta approved these changes

2023-01-19 11:42 UTC, tatsmaki requested changes

2023-01-19 11:42 UTC, tatsmaki commented on src/route/AppRouter.tsx
> +          <Route path={RoutePath.ERROR} element={<ErrorPage pageNotFound={true} />} />
\<ErrorPage pageNotFound \/\>
более короткая запись с передачей true пропа, они идентичны

2023-01-19 11:42 UTC, tatsmaki commented on src/index.tsx
> +    <ErrorBoundary>
может быть хорошей идеей оборачивать не весь апп, а секцию со страницами - чтобы оставить доступ к хедеру и боковому меню в случае ошибки

2023-01-19 12:01 UTC, tatsmaki approved these changes

2023-01-19 12:27 UTC, merged