Fix/bugs
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #82
Opened 2023-02-14 10:29 UTC by darnnng

1. пофиксила добавление в таблице employees
2. на breadcrumbs кликабельно имя юзера/cv
3. фиксы в datepickers
4. убран mode:'onChange' для модалок с созданием сущности и валидация идет по нажатию "submit"
5. небольшие фиксы на страницах чтоб привести их к общему виду
6. добавлен vercel.json
#81 #38

2023-02-14 13:35 UTC, DimaTeniuta requested changes

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/CvsPage/CreateCvModal/CreateCvModal.tsx
> +          <ModalWindowButton loading={createCvLoading} />
formState имеет поле isSubmitted (в значении false до первого сабмита) , можно использовать как `isValid={!isSubmitted || isValid}`

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/DepartmentsPage/DepartmentCreate/DepartmentCreateModal.tsx
> +          <ModalWindowButton loading={loading} />
Выше описал

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/EmployeesPage/EmployeesModal/EmployeesModal.tsx
> +  });
Не понятно зачем refetchQueries вместе с обновлением кеша вручную. Выбери что-нибудь одно
![image](https://user-images.githubusercontent.com/93836691/218751242-dbc0afa7-06e2-40db-bebd-2e57f52026b0.png)

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/EmployeesPage/EmployeesModal/EmployeesModal.tsx
> +          <ModalWindowButton loading={updateLoading} />
Выше писал

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/PositionsPage/CreatePositionModal/CreatePositionModal.tsx
> +    formState: { errors },
Выше писал

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/LanguagesPage/LanguageCreate/LanguageCreateModal.tsx
> +    formState: { errors },
Выше писал

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/EmployeesProfilePage/ProfileModal/ProfileModal.tsx
> -      await updateUser({
Также не нужный await в `CreateCvModal`

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/ProjectsPage/ProjectsCreateModal/ProjectsCreateModal.tsx
> +        updateCacheAfterCreatingProject(cache, data as CreateProjectResult);
`updateCacheAfterCreatingProject(cache, data!)`

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/ProjectsPage/ProjectsCreateModal/ProjectsCreateModal.tsx
> +          <ModalWindowButton loading={loading} />
Выше писал

2023-02-14 13:35 UTC, DimaTeniuta commented on src/components/pages/SkillsPage/SkillCreate/SkillCreateModal.tsx
> +          <ModalWindowButton loading={loading} />
Выше писал

2023-02-14 20:05 UTC, darnnng commented on src/components/pages/SkillsPage/SkillCreate/SkillCreateModal.tsx
> +          <ModalWindowButton loading={loading} />
исправила все

2023-02-15 06:55 UTC, DimaTeniuta requested changes

2023-02-15 06:55 UTC, DimaTeniuta commented on src/components/pages/EmployeesPage/EmployeesModal/EmployeesModal.tsx
> +    formState: { errors, isValid, isSubmitted },
В 21 строке указан не верный возвращаемый тип из за этого в 51 строке приведение типов. Изменив возвращаемы тип в 21 строке останется лишь в 51 указать что data не null и не undefined

2023-02-15 07:38 UTC, DimaTeniuta approved these changes

2023-02-23 11:22 UTC, tatsmaki approved these changes

2023-02-23 11:34 UTC, merged