Future/employee skills
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #83
Opened 2023-02-15 16:19 UTC by darnnng

1. Employee skills page 
2. Ability to add/delete user skill
![image](https://user-images.githubusercontent.com/87519112/219087515-ca73b0a9-4bcf-4ef9-89e2-6ed633037dd9.png)
![image](https://user-images.githubusercontent.com/87519112/219087671-e3294fb7-f477-4223-9b53-3a3c65e35a2c.png)

2023-02-15 19:46 UTC, DimaTeniuta requested changes

2023-02-15 19:46 UTC, DimaTeniuta commented on src/components/pages/EmployeesSkillsPage/EmployeesSkillsPage.tsx
> +        user: {
Функция для удаления skill, а используется мутация для обновления пользователя. Есть специальная мутация `deleteSkill` Возможно для получения id нужен запрос `skills` и обыграть ситуацию с отображением имени к примеру как на странице `cvs/:id/projects` в модалке

2023-02-15 19:46 UTC, DimaTeniuta commented on src/components/pages/EmployeesSkillsPage/SkillsModal/SkillsModal.tsx
> +  });
Поля наверно должны быть обязательными 
![image](https://user-images.githubusercontent.com/93836691/219129165-0a36b3fc-71fa-4f2f-b2b2-bf5493484637.png)

2023-02-15 19:46 UTC, DimaTeniuta commented on src/components/pages/EmployeesSkillsPage/SkillsModal/SkillsModal.tsx
> +        id: userId,
Есть мутация `updateSkill`

2023-02-15 19:46 UTC, DimaTeniuta commented on src/components/pages/EmployeesSkillsPage/EmployeesSkillsPage.tsx
> +              {data!.user.profile.skills.length > 0 ? (
`data!.user.profile.skills.length ? (` думаю будет достаточно, так как 0 это falsy значение

2023-02-15 19:46 UTC, DimaTeniuta commented on src/components/pages/EmployeesSkillsPage/SkillsList/SkillsList.styles.ts
> +  wordWrap: 'break-word',
на 320 px выглядит не очень(текст короткий но все же переносится), возможно изменение размера шрифта на мобильных разрешениях поможет
Также возможно стоит выровнять отображение, сейчас вот так 
![image](https://user-images.githubusercontent.com/93836691/219131141-4341702d-65ac-44b8-ac9a-da442d4ff840.png)
Можно попробовать сделать как-нибудь вот так
![image](https://user-images.githubusercontent.com/93836691/219131310-f4a56218-7bd7-455a-a176-5daae11f3056.png)

2023-02-15 19:46 UTC, DimaTeniuta commented on src/components/pages/EmployeesSkillsPage/SkillsModal/SkillsModal.tsx
> +            data={skillsData!.skills}
Не допускается повторение скилов, думаю нужно это учесть при возможности выбора

2023-02-15 19:46 UTC, DimaTeniuta commented on src/constants/skillsMastery.ts
> +}
Этот енум нужен лишь на одной странице. Может стоит хранить его в папке страницы
Поле Average  не используется. Нужно ли оно?

2023-02-15 19:46 UTC, DimaTeniuta commented on src/constants/fieldNameEmployeeSkillForm.ts
> +}
Этот енум нужен лишь на одной странице. Может стоит хранить его в папке страницы

2023-02-15 19:46 UTC, DimaTeniuta commented on src/components/pages/EmployeesSkillsPage/EmployeesSkillsPage.tsx
> +  });
хук useProfileFormData содержит уже этот запрос

2023-02-15 19:46 UTC, DimaTeniuta commented on src/hooks/useProfileFormData.ts
> +  ];
Хук был предназначен для другой страницы, теперь в нем очень много запросов. Думаю, если использовать запросы предназначенные для мутации skills, то данные о department и position будут не нужны

2023-02-15 19:46 UTC, DimaTeniuta commented on src/components/pages/EmployeesSkillsPage/SkillsList/SkillsList.tsx
> +              onClick={() => handleDelete({ skill_name, mastery })}
Через замыкание лучше сделать

2023-02-15 20:11 UTC, DimaTeniuta commented on src/components/pages/EmployeesSkillsPage/SkillsModal/SkillsModal.tsx
> +        id: userId,
Увидел что в мутациях skills нет поля mastery

2023-02-16 15:10 UTC, darnnng commented on src/components/pages/EmployeesSkillsPage/SkillsList/SkillsList.tsx
> +              onClick={() => handleDelete({ skill_name, mastery })}
пофиксила все

2023-02-17 17:48 UTC, DimaTeniuta approved these changes

2023-02-23 11:23 UTC, tatsmaki approved these changes

2023-02-23 11:31 UTC, merged