Future/employee projects translate
curriculum-vitae-team/cv-Tenyuta-Nagai pull request #95
Opened 2023-02-23 09:55 UTC by darnnng

translation of employee details, projects, projects details
#92 
#93

2023-02-23 10:47 UTC, DimaTeniuta requested changes

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/en.json
> +  "Domain:": "Domain:",
Переводы повторяются. Можно исправить в компоненте
![image](https://user-images.githubusercontent.com/93836691/220879365-e0a1ed62-b0e7-47c4-9040-9f96d27f98ab.png)

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/en.json
> +  "End date:": "End date:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/en.json
> +  "First name": "First name",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/en.json
> +  "Internal name:": "Internal name:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/en.json
> +  "Last name": "Last name",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/en.json
> +  "Name:": "Name:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/en.json
> +  "Start date:": "Start date:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/ru.json
> +  "Description:": "Описание:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/ru.json
> +  "Domain:": "Домен:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/ru.json
> +  "End date:": "Дата окончания:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/ru.json
> +  "Internal name:": "Внутреннее имя:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/ru.json
> +  "Name:": "Имя:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on public/locales/ru.json
> +  "Start date:": "Дата начала:",
Повтор

2023-02-23 10:47 UTC, DimaTeniuta commented on src/components/UI/AuthButtons/AuthButtons.tsx
> +          label={t('signup')}
Почему не обернуть значение енума в функцию t?

2023-02-23 10:47 UTC, DimaTeniuta commented on src/utils/validationSchema.ts
> +      startDate && schema.min(startDate, i18next.t('End date must be bigger than start date'))
функции t на поле ошибки будет достаточно

2023-02-23 10:47 UTC, DimaTeniuta commented on src/utils/validationSchema.ts
> +    .test('type', i18next.t('The file must be JPG, JPEG or PNG')!, (image) => {
функции t на поле ошибки будет достаточно
![image](https://user-images.githubusercontent.com/93836691/220883497-e5f65bb8-e888-4b50-bee8-f27092ae28c6.png)

2023-02-23 10:47 UTC, DimaTeniuta commented on src/utils/validationSchema.ts
> +    .test('fileSize', i18next.t('The file is too large')!, (image) => {
Выше описал

2023-02-24 11:48 UTC, darnnng commented on src/utils/validationSchema.ts
> +    .test('fileSize', i18next.t('The file is too large')!, (image) => {
исправила все

2023-02-25 16:43 UTC, DimaTeniuta approved these changes

2023-02-27 10:07 UTC, merged